Add diagonal ref. line to plot_predictions() function
carpentries-lab/deep-learning-intro pull request #476
Opened 2024-06-04 18:41 UTC by qualiaMachine

It's very useful to have a diagonal reference line when viewing scatterplots that plot true vs predicted data. Deviations above/below the diagonal tell you where the model is making more mistakes.

2024-06-11 06:28 UTC, svenvanderburg requested changes
Nice, I like the addition! This does change all the plots in this episode right? Can you upload the new images?

2024-06-11 16:56 UTC, svenvanderburg commented
Yes, I think it is a neat addition! If you have the time can you add the updated plots? (I think it is confusing if we only add the code and not the corresponding plots). If you don't have time we can pick it up during our next sprint.

By the way @qualiaMachine did you see we have an upcoming sprint 22 & 23rd of July? https://github.com/carpentries-incubator/deep-learning-intro?tab=readme-ov-file#lesson-development-sprints . Maybe you would like to join (in any form of capacity you have)?

2024-06-11 18:29 UTC, qualiaMachine commented
Happy to add the plots this week :). I wish I could make the sprints, but 10 CEST will be 3am in my time zone. Might have to skip that one haha.

2024-06-13 05:35 UTC, svenvanderburg commented
> Happy to add the plots this week :). I wish I could make the sprints, but 10 CEST will be 3am in my time zone. Might have to skip that one haha.

Check. If you are interested we could meet around 16:00 CEST, which would be 9:00 in your time zone then?

2025-05-01 14:37 UTC, carschno commented
Just to follow up on this: did you ever meet to discuss the issue? Is it still relevant, or was is resolved with changing the underlying dataset etc.?

2025-05-15 19:36 UTC, qualiaMachine commented
Finally got around to adding the figs. It might be easiest to make this pull request on the newly formatted Carpentries workbench version (this one operated on .Rmd files). I'll submit another pull request and close this one right after.

2025-05-15 19:45 UTC, closed without merging